name: C/C++ CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: ["main"]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: pkutyl/cpp_app
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build . -t cpp_app

      - name: Run Tests
        run: docker run cpp_app
